/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

// Integrantes: Lionny Lin - 0222510050 & Samuel Campo - 0222510057
// Universidad de Cartagena - POO 2026-1

import modelo.*;
import controlador.*;
import excepciones.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.Map;
import java.util.Map.Entry;
import grafo.*;
import java.awt.Color;

public class Interfaz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());

    private TarjetaUsuario tarjetaActual;
    private GestorRutas gestorRutas = new GestorRutas();
    private GestorTarjetas gestorTarjetas = new GestorTarjetas();
    private GestorAdmins gestorAdmins = new GestorAdmins();
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        // Bug 1 fix: jButton23 ("Limpiar Selección") no tenía ActionListener
        jButton23.addActionListener(this::jButton23ActionPerformed);
        // Bug 3 fix: configurar el spinner con rango 0-23 y valor inicial de la hora actual
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(
                java.time.LocalTime.now().getHour(), 0, 23, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        secciones = new javax.swing.JTabbedPane();
        seccionUsuario = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contenedorMovimientos = new javax.swing.JTextArea();
        jTextField10 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idTarjetaTexto = new javax.swing.JTextField();
        botonBuscarIdTarjeta = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        titularTarjetaTexto = new javax.swing.JLabel();
        saldoTarjetaTexto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonAgregarSaldo4 = new javax.swing.JButton();
        botonAgregarSaldo3 = new javax.swing.JButton();
        botonAgregarSaldo2 = new javax.swing.JButton();
        botonAgregarSaldo1 = new javax.swing.JButton();
        seccionAdministrador = new javax.swing.JPanel();
        administradorSecciones = new javax.swing.JTabbedPane();
        inicioDeSesion = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idAdminEntrada = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        claveAdminEntrada = new javax.swing.JTextField();
        botonEntrar = new javax.swing.JButton();
        rutasSeccion = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaRutas = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        hInicioEntrada = new javax.swing.JTextField();
        paradasEntrada = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nombreRutaEntrada = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        hFinEntrada = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pesosEntrada = new javax.swing.JTextField();
        guardarRutaBoton = new javax.swing.JButton();
        eliminarRutaBoton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        barrioEntrada = new javax.swing.JTextField();
        tarjetasSeccion = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaTarjetas = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        idTarjetaEntrada = new javax.swing.JTextField();
        saldoEntrada = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        crearTarjetaBoton = new javax.swing.JButton();
        eliminarTarjetaBoton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        seccionMapa = new javax.swing.JPanel();
        jTextField13 = new javax.swing.JTextField();
        crespo = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        estacionOrigenTexto = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        estacionDestinoTexto = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton23 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        contenedorGuia = new javax.swing.JTextArea();
        marbella = new javax.swing.JButton();
        chambacu = new javax.swing.JButton();
        bocagrande = new javax.swing.JButton();
        bodeguita = new javax.swing.JButton();
        manga = new javax.swing.JButton();
        pieDeLaPopa = new javax.swing.JButton();
        delicias = new javax.swing.JButton();
        ejecutivos = new javax.swing.JButton();
        olaya = new javax.swing.JButton();
        portal = new javax.swing.JButton();
        nelsonMandela = new javax.swing.JButton();
        bazurto = new javax.swing.JButton();
        zaragocilla = new javax.swing.JButton();
        sanFernando = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        secciones.addChangeListener(this::seccionesStateChanged);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Movimientos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        contenedorMovimientos.setColumns(20);
        contenedorMovimientos.setRows(5);
        contenedorMovimientos.setText("Sin movimientos.");
        jScrollPane1.setViewportView(contenedorMovimientos);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextField10.setBackground(new java.awt.Color(186, 183, 140));
        jTextField10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(0, 0, 0));
        jTextField10.setText("KIOSCO INFORMATIVO - TRANSMETRO");

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar tarjeta"));

        jLabel1.setText("ID de tarjeta");

        botonBuscarIdTarjeta.setBackground(new java.awt.Color(186, 183, 140));
        botonBuscarIdTarjeta.setForeground(new java.awt.Color(0, 0, 0));
        botonBuscarIdTarjeta.setText("Consultar");
        botonBuscarIdTarjeta.addActionListener(this::botonBuscarIdTarjetaActionPerformed);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(idTarjetaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(198, 198, 198)
                    .addComponent(botonBuscarIdTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(123, Short.MAX_VALUE)))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idTarjetaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(botonBuscarIdTarjeta)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(new java.awt.Color(186, 183, 140));

        titularTarjetaTexto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titularTarjetaTexto.setForeground(new java.awt.Color(0, 0, 0));
        titularTarjetaTexto.setText("Tarifa por viaje: $3.900");
        titularTarjetaTexto.setToolTipText("");

        saldoTarjetaTexto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        saldoTarjetaTexto.setForeground(new java.awt.Color(0, 0, 0));
        saldoTarjetaTexto.setText("Saldo: --");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Sin tarjeta consultada");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saldoTarjetaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titularTarjetaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(603, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saldoTarjetaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titularTarjetaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        botonAgregarSaldo4.setBackground(new java.awt.Color(190, 140, 107));
        botonAgregarSaldo4.setForeground(new java.awt.Color(0, 0, 0));
        botonAgregarSaldo4.setText("+50.000");
        botonAgregarSaldo4.addActionListener(this::botonAgregarSaldo4ActionPerformed);

        botonAgregarSaldo3.setBackground(new java.awt.Color(190, 140, 107));
        botonAgregarSaldo3.setForeground(new java.awt.Color(0, 0, 0));
        botonAgregarSaldo3.setText("+20.000");
        botonAgregarSaldo3.addActionListener(this::botonAgregarSaldo3ActionPerformed);

        botonAgregarSaldo2.setBackground(new java.awt.Color(190, 140, 107));
        botonAgregarSaldo2.setForeground(new java.awt.Color(0, 0, 0));
        botonAgregarSaldo2.setText("+10.000");
        botonAgregarSaldo2.addActionListener(this::botonAgregarSaldo2ActionPerformed);

        botonAgregarSaldo1.setBackground(new java.awt.Color(190, 140, 107));
        botonAgregarSaldo1.setForeground(new java.awt.Color(0, 0, 0));
        botonAgregarSaldo1.setText("+5.000");
        botonAgregarSaldo1.addActionListener(this::botonAgregarSaldo1ActionPerformed);

        javax.swing.GroupLayout seccionUsuarioLayout = new javax.swing.GroupLayout(seccionUsuario);
        seccionUsuario.setLayout(seccionUsuarioLayout);
        seccionUsuarioLayout.setHorizontalGroup(
            seccionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField10)
            .addGroup(seccionUsuarioLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(seccionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(seccionUsuarioLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(botonAgregarSaldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonAgregarSaldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonAgregarSaldo3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonAgregarSaldo4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        seccionUsuarioLayout.setVerticalGroup(
            seccionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seccionUsuarioLayout.createSequentialGroup()
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(seccionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregarSaldo1)
                    .addComponent(botonAgregarSaldo2)
                    .addComponent(botonAgregarSaldo3)
                    .addComponent(botonAgregarSaldo4))
                .addGap(32, 32, 32)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        secciones.addTab("Usuario", seccionUsuario);

        jPanel1.setBackground(new java.awt.Color(186, 183, 140));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("ID (Admin):");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Inicio de Sesión Para Administradores");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Contraseña:");

        botonEntrar.setBackground(new java.awt.Color(186, 183, 140));
        botonEntrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonEntrar.setForeground(new java.awt.Color(0, 0, 0));
        botonEntrar.setText("Entrar");
        botonEntrar.addActionListener(this::botonEntrarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(claveAdminEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idAdminEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idAdminEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(claveAdminEntrada))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(botonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout inicioDeSesionLayout = new javax.swing.GroupLayout(inicioDeSesion);
        inicioDeSesion.setLayout(inicioDeSesionLayout);
        inicioDeSesionLayout.setHorizontalGroup(
            inicioDeSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicioDeSesionLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        inicioDeSesionLayout.setVerticalGroup(
            inicioDeSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioDeSesionLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        administradorSecciones.addTab("Inicio de Sesion", inicioDeSesion);

        jLabel6.setText("Rutas registradas");

        tablaRutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Troncal", "T101", null, "5:00", "21:00", "Portal, Ejecutivos, Las Delicias"},
                {"Troncal", "T102", null, "5:00", "21:00", "Portal, Bocagrande, Las delicias"},
                {"Troncal", "T103", null, "5:00", "21:00", "Portal, Ejecutivos, Chambacu"},
                {"Alimentadora", "A103", null, "5:00", "20:00", "Chambacu, Manga, Pie de la popa"},
                {"Alimentadora", "A205", null, "5:00", "20:00", "Chambacu, Crespo, Manga"},
                {"Alimentadora", "A310", null, "5:00", "19:00", "Las delicias, Olaya, Nelson mandela"}
            },
            new String [] {
                "Tipo", "Nombre", "Pesos", "H.Inicio", "H.Fin", "Paradas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaRutas);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar nueva ruta"));

        jLabel7.setText("Tipo: ");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Troncal", "Alimentadora" }));

        jLabel8.setText("H.inicio:");

        jLabel9.setText("Paradas");

        jLabel10.setText("Nombre");

        jLabel11.setText("H.fin");

        jLabel12.setText("Pesos");

        guardarRutaBoton.setBackground(new java.awt.Color(0, 51, 153));
        guardarRutaBoton.setForeground(new java.awt.Color(255, 255, 255));
        guardarRutaBoton.setText("Guardar ruta");
        guardarRutaBoton.addActionListener(this::guardarRutaBotonActionPerformed);

        eliminarRutaBoton.setBackground(new java.awt.Color(204, 0, 0));
        eliminarRutaBoton.setForeground(new java.awt.Color(255, 255, 255));
        eliminarRutaBoton.setText("Eliminar ruta");
        eliminarRutaBoton.addActionListener(this::eliminarRutaBotonActionPerformed);

        jLabel16.setText("Barrio");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paradasEntrada)
                            .addComponent(comboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hInicioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(158, 158, 158)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(pesosEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(nombreRutaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(hFinEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(guardarRutaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarRutaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(barrioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(nombreRutaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(hInicioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(hFinEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paradasEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(pesosEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(barrioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(guardarRutaBoton)
                        .addComponent(eliminarRutaBoton)))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rutasSeccionLayout = new javax.swing.GroupLayout(rutasSeccion);
        rutasSeccion.setLayout(rutasSeccionLayout);
        rutasSeccionLayout.setHorizontalGroup(
            rutasSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rutasSeccionLayout.createSequentialGroup()
                .addGroup(rutasSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rutasSeccionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(rutasSeccionLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(rutasSeccionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        rutasSeccionLayout.setVerticalGroup(
            rutasSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rutasSeccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        administradorSecciones.addTab("Gestion de Rutas", rutasSeccion);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tarjetas registradas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tablaTarjetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"TC-0001", "Carlos Perez", "$15000"},
                {"TC-0002", "Maria Lopez", "$8500"},
                {"TC-0003", "Juan Herrera", "$312000"},
                {"TC-0004", "Maria", "$120000"}
            },
            new String [] {
                "Numero", "Saldo", "Movimientos"
            }
        ));
        jScrollPane3.setViewportView(tablaTarjetas);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear / Eliminar tarjeta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel13.setText("ID:");

        jLabel15.setText("Saldo inicial:");

        crearTarjetaBoton.setBackground(new java.awt.Color(0, 51, 153));
        crearTarjetaBoton.setForeground(new java.awt.Color(255, 255, 255));
        crearTarjetaBoton.setText("Crear tarjeta");
        crearTarjetaBoton.addActionListener(this::crearTarjetaBotonActionPerformed);

        eliminarTarjetaBoton.setBackground(new java.awt.Color(204, 0, 0));
        eliminarTarjetaBoton.setForeground(new java.awt.Color(255, 255, 255));
        eliminarTarjetaBoton.setText("Eliminar tarjeta");
        eliminarTarjetaBoton.addActionListener(this::eliminarTarjetaBotonActionPerformed);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(crearTarjetaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarTarjetaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(31, 31, 31)
                            .addComponent(saldoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(86, 86, 86)
                            .addComponent(idTarjetaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(581, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(idTarjetaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(saldoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearTarjetaBoton)
                    .addComponent(eliminarTarjetaBoton))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tarjetasSeccionLayout = new javax.swing.GroupLayout(tarjetasSeccion);
        tarjetasSeccion.setLayout(tarjetasSeccionLayout);
        tarjetasSeccionLayout.setHorizontalGroup(
            tarjetasSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetasSeccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tarjetasSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tarjetasSeccionLayout.setVerticalGroup(
            tarjetasSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetasSeccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        administradorSecciones.addTab("Gestion de Tarjetas", tarjetasSeccion);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("Panel de administrador");

        jTextField11.setBackground(new java.awt.Color(186, 183, 140));
        jTextField11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(0, 0, 0));
        jTextField11.setText("KIOSCO INFORMATIVO - TRANSCARIBE");
        jTextField11.addActionListener(this::jTextField11ActionPerformed);

        jTextField12.setBackground(new java.awt.Color(186, 183, 140));
        jTextField12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(0, 0, 0));
        jTextField12.setText("KIOSCO INFORMATIVO - TRANSMETRO");

        javax.swing.GroupLayout seccionAdministradorLayout = new javax.swing.GroupLayout(seccionAdministrador);
        seccionAdministrador.setLayout(seccionAdministradorLayout);
        seccionAdministradorLayout.setHorizontalGroup(
            seccionAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seccionAdministradorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seccionAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(administradorSecciones)
                    .addGroup(seccionAdministradorLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jTextField12)
            .addGroup(seccionAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(seccionAdministradorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTextField11)
                    .addContainerGap()))
        );
        seccionAdministradorLayout.setVerticalGroup(
            seccionAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seccionAdministradorLayout.createSequentialGroup()
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(administradorSecciones)
                .addContainerGap())
            .addGroup(seccionAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(seccionAdministradorLayout.createSequentialGroup()
                    .addGap(287, 287, 287)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(477, Short.MAX_VALUE)))
        );

        secciones.addTab("Administrador", seccionAdministrador);

        jTextField13.setBackground(new java.awt.Color(186, 183, 140));
        jTextField13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(0, 0, 0));
        jTextField13.setText("KIOSCO INFORMATIVO - TRANSMETRO");

        crespo.setText("Crespo");
        crespo.addActionListener(this::crespoActionPerformed);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Información de mapa"));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Selección"));

        jLabel17.setText("Origen");

        estacionOrigenTexto.setText("[Haga clic en el mapa]");

        jLabel18.setText("Destino");

        estacionDestinoTexto.setText("[Haga clic en el mapa]");

        jLabel19.setText("Hora (0h - 23h): ");

        jButton23.setText("Limpiar Selección");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estacionOrigenTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estacionDestinoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(estacionOrigenTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(estacionDestinoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton23)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("Guía De Ruta Recomendada"));

        contenedorGuia.setColumns(20);
        contenedorGuia.setRows(5);
        jScrollPane4.setViewportView(contenedorGuia);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4)))
                .addContainerGap())
        );

        marbella.setText("Marbella");
        marbella.addActionListener(this::marbellaActionPerformed);

        chambacu.setText("Chambacú");
        chambacu.addActionListener(this::chambacuActionPerformed);

        bocagrande.setText("Bocagrande");
        bocagrande.addActionListener(this::bocagrandeActionPerformed);

        bodeguita.setText("Bodeguita");
        bodeguita.addActionListener(this::bodeguitaActionPerformed);

        manga.setText("Manga");
        manga.addActionListener(this::mangaActionPerformed);

        pieDeLaPopa.setText("Pie de la Popa");
        pieDeLaPopa.addActionListener(this::pieDeLaPopaActionPerformed);

        delicias.setText("Las Delicias");
        delicias.addActionListener(this::deliciasActionPerformed);

        ejecutivos.setText("Ejecutivos");
        ejecutivos.addActionListener(this::ejecutivosActionPerformed);

        olaya.setText("Olaya");
        olaya.addActionListener(this::olayaActionPerformed);

        portal.setText("Portal");
        portal.addActionListener(this::portalActionPerformed);

        nelsonMandela.setText("Nelson Mandela");
        nelsonMandela.addActionListener(this::nelsonMandelaActionPerformed);

        bazurto.setText("Bazurto");
        bazurto.addActionListener(this::bazurtoActionPerformed);

        zaragocilla.setText("Zaragocilla");
        zaragocilla.addActionListener(this::zaragocillaActionPerformed);

        sanFernando.setText("San Fernando");
        sanFernando.addActionListener(this::sanFernandoActionPerformed);

        javax.swing.GroupLayout seccionMapaLayout = new javax.swing.GroupLayout(seccionMapa);
        seccionMapa.setLayout(seccionMapaLayout);
        seccionMapaLayout.setHorizontalGroup(
            seccionMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seccionMapaLayout.createSequentialGroup()
                .addGap(0, 307, Short.MAX_VALUE)
                .addGroup(seccionMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seccionMapaLayout.createSequentialGroup()
                        .addGroup(seccionMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(seccionMapaLayout.createSequentialGroup()
                                .addComponent(zaragocilla, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(172, 172, 172))
                            .addGroup(seccionMapaLayout.createSequentialGroup()
                                .addComponent(sanFernando, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)))
                        .addComponent(olaya, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(portal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seccionMapaLayout.createSequentialGroup()
                        .addComponent(nelsonMandela, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))))
            .addGroup(seccionMapaLayout.createSequentialGroup()
                .addGroup(seccionMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seccionMapaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(bocagrande, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seccionMapaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(manga, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(seccionMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seccionMapaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pieDeLaPopa, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(bazurto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(seccionMapaLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(delicias, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(seccionMapaLayout.createSequentialGroup()
                .addGroup(seccionMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seccionMapaLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(marbella, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(crespo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(seccionMapaLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(chambacu, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ejecutivos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(seccionMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(seccionMapaLayout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(bodeguita, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(774, Short.MAX_VALUE)))
        );
        seccionMapaLayout.setVerticalGroup(
            seccionMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seccionMapaLayout.createSequentialGroup()
                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(seccionMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seccionMapaLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(bocagrande, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(seccionMapaLayout.createSequentialGroup()
                        .addGroup(seccionMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(seccionMapaLayout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(pieDeLaPopa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(delicias, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(seccionMapaLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(ejecutivos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(bazurto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(seccionMapaLayout.createSequentialGroup()
                                .addGroup(seccionMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(seccionMapaLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(crespo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(seccionMapaLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(marbella, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)
                                .addComponent(chambacu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(manga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)))
                        .addGroup(seccionMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(seccionMapaLayout.createSequentialGroup()
                                .addGroup(seccionMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(seccionMapaLayout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(portal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(seccionMapaLayout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addGroup(seccionMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(olaya, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sanFernando, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(20, 20, 20)
                                .addComponent(nelsonMandela, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(zaragocilla, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(seccionMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(seccionMapaLayout.createSequentialGroup()
                    .addGap(198, 198, 198)
                    .addComponent(bodeguita, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(579, Short.MAX_VALUE)))
        );

        secciones.addTab("Mapa", seccionMapa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(secciones)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(secciones)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Administrador administradorActual;
    /*-----------------------------Interfaz de usuario-----------------------------------------*/
    private void botonAgregarSaldo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarSaldo1ActionPerformed
        // TODO add your handling code here:
        recargarMonto(5000);
    }//GEN-LAST:event_botonAgregarSaldo1ActionPerformed

    private void botonAgregarSaldo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarSaldo2ActionPerformed
        // TODO add your handling code here:
        recargarMonto(10000);
    }//GEN-LAST:event_botonAgregarSaldo2ActionPerformed

    private void botonAgregarSaldo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarSaldo3ActionPerformed
        // TODO add your handling code here:
        recargarMonto(20000);
    }//GEN-LAST:event_botonAgregarSaldo3ActionPerformed

    private void botonAgregarSaldo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarSaldo4ActionPerformed
        // TODO add your handling code here:
        recargarMonto(50000);
    }//GEN-LAST:event_botonAgregarSaldo4ActionPerformed

    private void seccionesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_seccionesStateChanged
        // TODO add your handling code here:
        mostrarTablaRutas();
        mostrarTablaTarjetas();
        mostrarGrafo();

        if (administradorSecciones.getTabCount() > 0 && administradorSecciones.getSelectedIndex() != -1)
            administradorSecciones.setSelectedIndex(0);
        administradorSecciones.setEnabled(false);


        administradorActual = null;

    }//GEN-LAST:event_seccionesStateChanged

    private void guardarRutaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarRutaBotonActionPerformed
        // TODO add your handling code here:
        try{
            Ruta rutaCreada;

            String entradaNombre = nombreRutaEntrada.getText();

            if(existeRuta(entradaNombre))
                throw new Exception("Ya existe una ruta con ese nombre");

            if(entradaNombre.length() < 2)
                throw new Exception("El nombre de la ruta es demasiado corto");

            int hInicio, hFin;

            hInicio = Integer.parseInt(hInicioEntrada.getText());
            hFin = Integer.parseInt(hFinEntrada.getText());

            ArrayList<String> paradas = new ArrayList<>();

            for(String parada : paradasEntrada.getText().split(",")) {
                paradas.add(parada);
            }

            ArrayList<Integer> pesos = new ArrayList<>();

            for(String peso : pesosEntrada.getText().split(",")){
                pesos.add(Integer.parseInt(peso));
            }

            rutaCreada = (comboTipo.getSelectedIndex() == 0) ?
                    new RutaTroncal(entradaNombre, hInicio, hFin, paradas, pesos) :
                    new RutaAlimentadora(entradaNombre, hInicio, hFin, paradas, barrioEntrada.getText(), pesos);

            gestorRutas.agregarRuta(rutaCreada);
            mostrarTablaRutas();

            JOptionPane.showMessageDialog(null, "Ruta creada con exito: " + entradaNombre, "Ruta creada", JOptionPane.DEFAULT_OPTION);

            //Limpiar las entradas
            limpiarRutaEntradas();


        }catch (NumberFormatException  e){
            JOptionPane.showMessageDialog(null, "Una de las horas o pesos es un valor no numerico", "Error", JOptionPane.ERROR_MESSAGE);

        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_guardarRutaBotonActionPerformed

    private void eliminarRutaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarRutaBotonActionPerformed
        // TODO add your handling code here:

        try{

            String entradaNombre = nombreRutaEntrada.getText();

            if(!existeRuta(entradaNombre))
                throw new Exception("No existe ninguna ruta con ese nombre: " + entradaNombre);

            gestorRutas.eliminarRuta(entradaNombre);

            JOptionPane.showMessageDialog(null, "Ruta Eliminada Con Exito: " + entradaNombre, "Ruta Eliminada", JOptionPane.DEFAULT_OPTION);

            mostrarTablaRutas();
            limpiarRutaEntradas();

        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }



    }//GEN-LAST:event_eliminarRutaBotonActionPerformed

    private void crearTarjetaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearTarjetaBotonActionPerformed
        // TODO add your handling code here:

        try{
            String numero = idTarjetaEntrada.getText();
            if(existeTarjeta(numero))
                throw new Exception("Ya existe una tarjeta registrada con ese numero");

            int saldoInicial = Integer.parseInt(saldoEntrada.getText());

            TarjetaUsuario tarjeta = new TarjetaUsuario(numero, saldoInicial);

            gestorTarjetas.crearTarjeta(tarjeta);

            JOptionPane.showMessageDialog(null, "tarjeta creada con exito: " + numero, "Tarjeta creada", JOptionPane.DEFAULT_OPTION);

            mostrarTablaTarjetas();

            limpiarTarjetaEntradas();



        }catch (NumberFormatException  e){
            JOptionPane.showMessageDialog(null, "El saldo inicial debe ser un valor numerico", "Error", JOptionPane.ERROR_MESSAGE);

        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_crearTarjetaBotonActionPerformed

    private void eliminarTarjetaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTarjetaBotonActionPerformed
        // TODO add your handling code here:
        try{
            String numero = idTarjetaEntrada.getText();

            if(!existeTarjeta(numero))
                throw new Exception("No existe ninguna tarjeta con el numero: " + numero);

            gestorTarjetas.eliminarTarjeta(numero);

            JOptionPane.showMessageDialog(null, "Tarjeta Eliminada Con Exito: " + numero, "Tarjeta Eliminada", JOptionPane.DEFAULT_OPTION);

            mostrarTablaTarjetas();
            limpiarTarjetaEntradas();


        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_eliminarTarjetaBotonActionPerformed


    private void botonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntrarActionPerformed
        // TODO add your handling code here:

        try{

            String idAdmin = idAdminEntrada.getText();
            String claveAdmin = claveAdminEntrada.getText();

            if(idAdmin.length() < 3 || claveAdmin.length() < 4)
                throw new Exception("Los datos de inicio de sesion son muy cortos o nulos");

            administradorActual = gestorAdmins.iniciarSesion(idAdmin, claveAdmin);

            if(administradorActual != null){
                JOptionPane.showMessageDialog(null, "Bienvenido: " + administradorActual.getNombre(), "Sesion Iniciada", JOptionPane.DEFAULT_OPTION);

                administradorSecciones.setEnabled(true);

                idAdminEntrada.setText("");
                claveAdminEntrada.setText("");

            }




        }catch (CredencialesInvalidasException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }



    }//GEN-LAST:event_botonEntrarActionPerformed

    private void marbellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marbellaActionPerformed
        // TODO add your handling code here:
        escogerEstacion("Marbella");
    }//GEN-LAST:event_marbellaActionPerformed

    private void crespoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crespoActionPerformed
        // TODO add your handling code here:
        escogerEstacion("Crespo");
    }//GEN-LAST:event_crespoActionPerformed

    private void chambacuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chambacuActionPerformed
        // TODO add your handling code here:
        escogerEstacion("Chambacú");
    }//GEN-LAST:event_chambacuActionPerformed

    private void mangaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangaActionPerformed
        // TODO add your handling code here:
        escogerEstacion("Manga");
    }//GEN-LAST:event_mangaActionPerformed

    private void bodeguitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodeguitaActionPerformed
        // TODO add your handling code here:
        escogerEstacion("La Bodeguita");
    }//GEN-LAST:event_bodeguitaActionPerformed

    private void bocagrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bocagrandeActionPerformed
        // TODO add your handling code here:
        escogerEstacion("Bocagrande");
    }//GEN-LAST:event_bocagrandeActionPerformed

    private void pieDeLaPopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieDeLaPopaActionPerformed
        // TODO add your handling code here:
        escogerEstacion("Pie de la Popa");
    }//GEN-LAST:event_pieDeLaPopaActionPerformed

    private void deliciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliciasActionPerformed
        // TODO add your handling code here:
        escogerEstacion("Las Delicias");
    }//GEN-LAST:event_deliciasActionPerformed

    private void zaragocillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zaragocillaActionPerformed
        // TODO add your handling code here:
        escogerEstacion("Zaragocilla");
    }//GEN-LAST:event_zaragocillaActionPerformed

    private void bazurtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bazurtoActionPerformed
        // TODO add your handling code here:
        escogerEstacion("Bazurto");
    }//GEN-LAST:event_bazurtoActionPerformed

    private void ejecutivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutivosActionPerformed
        // TODO add your handling code here:
        escogerEstacion("Ejecutivos");
    }//GEN-LAST:event_ejecutivosActionPerformed

    private void sanFernandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanFernandoActionPerformed
        // TODO add your handling code here:
        escogerEstacion("San Fernando");
    }//GEN-LAST:event_sanFernandoActionPerformed

    private void olayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olayaActionPerformed
        // TODO add your handling code here:
        escogerEstacion("Olaya");
    }//GEN-LAST:event_olayaActionPerformed

    private void portalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portalActionPerformed
        // TODO add your handling code here:
        escogerEstacion("Portal");
    }//GEN-LAST:event_portalActionPerformed

    private void nelsonMandelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nelsonMandelaActionPerformed
        // TODO add your handling code here:
        escogerEstacion("Nelson Mandela");
    }//GEN-LAST:event_nelsonMandelaActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private boolean existeTarjeta(String numero){

        for (TarjetaUsuario tarjeta: gestorTarjetas.getTarjetas()){
            if(tarjeta.getNumeroTarjeta().equalsIgnoreCase(numero))
                return true;
        }
        return false;
    }

    private boolean existeRuta(String nombre){

        for(Ruta ruta: gestorRutas.getRutas()){
            if(ruta.getNombreRuta().equalsIgnoreCase(nombreRutaEntrada.getText()))
                return true;
        }
        return false;
    }

    private void limpiarRutaEntradas(){
        nombreRutaEntrada.setText("");
        hInicioEntrada.setText("");
        hFinEntrada.setText("");
        paradasEntrada.setText("");
        pesosEntrada.setText("");
        barrioEntrada.setText("");
    }
    private void limpiarTarjetaEntradas(){
        idTarjetaEntrada.setText("");
        saldoEntrada.setText("");
    }


    private void recargarMonto(int monto){
        GestorTarjetas gestor = new GestorTarjetas();

        try{

            gestor.recargarTarjeta(tarjetaActual.getNumeroTarjeta(), monto);
            //tarjeta.recargar(monto);

            mostrarInformacionTarjeta(gestor.buscarPorNumero(tarjetaActual.getNumeroTarjeta()));
        }catch (NullPointerException e){
            JOptionPane.showMessageDialog(null, "No hay ninguna tarjeta ingresada", "Error", JOptionPane.ERROR_MESSAGE);

        }catch (TarjetaNoEncontradaException e){
            JOptionPane.showMessageDialog(null, "No se ha encontrado ninguna tarjeta", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }

    private void botonBuscarIdTarjetaActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
        String entrada = idTarjetaTexto.getText();

        tarjetaActual = buscarTarjeta(entrada);

        if(tarjetaActual != null){
            mostrarInformacionTarjeta(tarjetaActual);
        }

        
    }
    private void mostrarInformacionTarjeta(TarjetaUsuario tarjeta){
        //titularTarjetaTexto.setText("Usuario: " + tarjeta.getTitular());
        jLabel4.setText("Tarjeta: " + tarjeta.getNumeroTarjeta());
        saldoTarjetaTexto.setText("Saldo: $" + String.format("%.0f", tarjeta.getSaldo()));
        contenedorMovimientos.setText(tarjeta.getResumenMovimientos());

        // --- PRUEBA PARA LA CONSOLA ---
        System.out.println("Buscando tarjeta: " + tarjetaActual.getNumeroTarjeta());
        System.out.println("Cantidad de movimientos leidos: " + tarjetaActual.getMovimientos().size());
    }
    private TarjetaUsuario buscarTarjeta(String id){

        try{
            TarjetaUsuario tarjeta = gestorTarjetas.buscarPorNumero(id);
            return  tarjeta;

        }catch(TarjetaNoEncontradaException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error inesperado", JOptionPane.ERROR_MESSAGE);

        }
        return null;
    }

    /*-------------------------------------Interfaz de administrador-------------------------------------------*/
    private void mostrarTablaRutas(){

        DefaultTableModel table = (DefaultTableModel)tablaRutas.getModel();

        table.setRowCount(0);

        //table.addRow(new Object[]{"Tipo", "Nombre", "Pesos", "H.Inicio", "H.Fin", "Paradas"});
        for(int i = 0; i < gestorRutas.getRutas().size(); i ++){
            Ruta ruta = gestorRutas.getRutas().get(i);
            table.addRow(new Object[]{
                    ruta.getTipo() ,
                    ruta.getNombreRuta(),
                    ruta.getPesosTramos(),
                    ruta.getHoraInicio() + ":00", ruta.getHoraFin() + ":00",
                    ruta.getListadoParadas()
            });
        }
    }
    private void mostrarTablaTarjetas(){


        DefaultTableModel table = (DefaultTableModel) tablaTarjetas.getModel();
        table.setRowCount(0);

        for(int i = 0; i < gestorTarjetas.getTarjetas().size(); i ++){
            TarjetaUsuario tarjeta = gestorTarjetas.getTarjetas().get(i);
            table.addRow(new Object[]{tarjeta.getNumeroTarjeta(), tarjeta.getSaldo(), tarjeta.getResumenMovimientos()});
        }
    }

    /*----------------------------------Interfaz de mapa--------------------------------------------------------*/
    // Variables para controlar la selección secuencial de estaciones
    private String estacionOrigen = null;
    private String estacionDestino = null;


    private void mostrarGrafo(){
        dibujarTodasLasRutas();
    }
    public void escogerEstacion(String nombreEstacion) {
        if (estacionOrigen == null) {
            // Primer clic: configuramos el punto de partida
            estacionOrigen = nombreEstacion;
            estacionOrigenTexto.setText(estacionOrigen);
            estacionDestinoTexto.setText("Ahora seleccione el destino presionando otro nodo.");
            contenedorGuia.setText(""); // Limpiamos la guía anterior para el nuevo viaje
        } else {
            // Segundo clic: configuramos el punto de llegada
            estacionDestino = nombreEstacion;
            estacionDestinoTexto.setText(estacionDestino);

            // Ejecutamos la búsqueda de la ruta y la impresión de la guía
            generarGuiaDeViaje(estacionOrigen, estacionDestino);

            // Reiniciamos el estado para que la próxima selección empiece de cero
            estacionOrigen = null;
            estacionDestino = null;
        }
    }


private void generarGuiaDeViaje(String origen, String destino) {
    int horaSimulada = 12; // Hora base de simulación
    horaSimulada = (int) jSpinner1.getValue();

    try {
        // 1. Delegamos la búsqueda al controlador
        java.util.List<String> camino = gestorRutas.buscarRutaOptima(origen, destino, horaSimulada);

        // 2. Obtenemos el String formateado directamente del controlador y lo imprimimos
        String instrucciones = gestorRutas.generarInstrucciones(camino, horaSimulada);
        contenedorGuia.setText(instrucciones);

        // 3. Registramos la consulta en el historial
        modelo.RegistroConsulta historial = new modelo.RegistroConsulta(origen, destino, String.join(" -> ", camino), horaSimulada);
        historial.registrar();

    // 4. Manejo de excepciones personalizadas y activación de contingencia
    } catch (excepciones.OrigenDestinoIdenticoException e) {
        contenedorGuia.setText("Error: " + e.getMessage());
    } catch (excepciones.FueraDeServicioException e) {
        contenedorGuia.setText("Error: " + e.getMessage());
    } catch (excepciones.RutaNoEncontradaException e) {
        String contingencia = gestorRutas.generarContingencia(destino);
        contenedorGuia.setText("No se encontró ruta disponible.\n" + contingencia);
    } catch (Exception e) {
        contenedorGuia.setText("Ocurrió un error inesperado al procesar la ruta:\n" + e.getMessage());
    }
}
    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {
        estacionOrigen = null;
        estacionDestino = null;
        estacionOrigenTexto.setText("[Haga clic en el mapa]");
        estacionDestinoTexto.setText("[Haga clic en el mapa]");
        contenedorGuia.setText("");
    }

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane administradorSecciones;
    private javax.swing.JTextField barrioEntrada;
    private javax.swing.JButton bazurto;
    private javax.swing.JButton bocagrande;
    private javax.swing.JButton bodeguita;
    private javax.swing.JButton botonAgregarSaldo1;
    private javax.swing.JButton botonAgregarSaldo2;
    private javax.swing.JButton botonAgregarSaldo3;
    private javax.swing.JButton botonAgregarSaldo4;
    private javax.swing.JButton botonBuscarIdTarjeta;
    private javax.swing.JButton botonEntrar;
    private javax.swing.JButton chambacu;
    private javax.swing.JTextField claveAdminEntrada;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JTextArea contenedorGuia;
    private javax.swing.JTextArea contenedorMovimientos;
    private javax.swing.JButton crearTarjetaBoton;
    private javax.swing.JButton crespo;
    private javax.swing.JButton delicias;
    private javax.swing.JButton ejecutivos;
    private javax.swing.JButton eliminarRutaBoton;
    private javax.swing.JButton eliminarTarjetaBoton;
    private javax.swing.JTextField estacionDestinoTexto;
    private javax.swing.JTextField estacionOrigenTexto;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton guardarRutaBoton;
    private javax.swing.JTextField hFinEntrada;
    private javax.swing.JTextField hInicioEntrada;
    private javax.swing.JTextField idAdminEntrada;
    private javax.swing.JTextField idTarjetaEntrada;
    private javax.swing.JTextField idTarjetaTexto;
    private javax.swing.JPanel inicioDeSesion;
    private javax.swing.JButton jButton23;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JButton manga;
    private javax.swing.JButton marbella;
    private javax.swing.JButton nelsonMandela;
    private javax.swing.JTextField nombreRutaEntrada;
    private javax.swing.JButton olaya;
    private javax.swing.JTextField paradasEntrada;
    private javax.swing.JTextField pesosEntrada;
    private javax.swing.JButton pieDeLaPopa;
    private javax.swing.JButton portal;
    private javax.swing.JPanel rutasSeccion;
    private javax.swing.JTextField saldoEntrada;
    private javax.swing.JLabel saldoTarjetaTexto;
    private javax.swing.JButton sanFernando;
    private javax.swing.JPanel seccionAdministrador;
    private javax.swing.JPanel seccionMapa;
    private javax.swing.JPanel seccionUsuario;
    private javax.swing.JTabbedPane secciones;
    private javax.swing.JTable tablaRutas;
    private javax.swing.JTable tablaTarjetas;
    private javax.swing.JPanel tarjetasSeccion;
    private javax.swing.JLabel titularTarjetaTexto;
    private javax.swing.JButton zaragocilla;
    // End of variables declaration//GEN-END:variables

    /*private JButton getNode(String str){
        Map <String, JButton> nodes = Map.of();

        nodes.put("Ejecutivos",ejecutivos);
        nodes.put("Crespo", crespo);
        nodes.put("Chambacu", chambacu);
        nodes.put("Manga", manga);
        nodes.put("Bodeguita", bodeguita);
        nodes.put("Bocagrande", bocagrande);
        nodes.put("Pie de la Popa", pieDeLaPopa);
        nodes.put("Zaragocilla", zaragocilla);
        nodes.put("San Fernando", sanFernando);
        nodes.put("Olaya", olaya);
        nodes.put("Patio Portal", portal);
        nodes.put("Nelson Mandela", nelsonMandela);

        return nodes.get(str);
    }*/
    private JButton obtenerBotonEstacion(String nombreParada) {
        // Normalizamos el texto (minúsculas y sin espacios extra) para evitar errores
        String nombre = nombreParada.trim();

        switch (nombre) {
            case "Portal": return portal; // O como se llame la variable de tu botón
            case "Ejecutivos": return ejecutivos;
            case "Crespo": return crespo;
            case "Chambacú": return chambacu;
            case "Manga": return manga;
            case "La Bodeguita": return bodeguita;
            case "Bocagrande": return bocagrande;
            case "Pie de la Popa": return pieDeLaPopa;
            case "Zaragocilla": return zaragocilla;
            case "San Fernando": return sanFernando;
            case "Marbella": return marbella;
            case "Nelson Mandela": return nelsonMandela;
            case "Olaya": return olaya;
            case "Bazurto": return bazurto;
            case "Las Delicias":return delicias;
            // Agrega aquí el resto de botones que tengas en tu mapa
            default:
                System.out.println("No se encontró el botón para: " + nombreParada);
                return null;
        }
    }
    public void dibujarTodasLasRutas() {
        
        java.awt.Component[] componentes = seccionMapa.getComponents();
        for (java.awt.Component c : componentes) {
            if (c instanceof PanelMapaRutas) {
                seccionMapa.remove(c);
            }
        }

        seccionMapa.setLayout(null);

        PanelMapaRutas panelMapa = new PanelMapaRutas();
        panelMapa.setBounds(0, 0, seccionMapa.getWidth(), seccionMapa.getHeight());
        panelMapa.setOpaque(false);

        GestorRutas gestorLocal = new GestorRutas();

        for (Ruta ruta : gestorLocal.getRutas()) {
            Color colorRuta;
            if (ruta.getTipo().equalsIgnoreCase("Troncal")) {
                colorRuta = new Color(220, 20, 60);
            } else if (ruta.getTipo().equalsIgnoreCase("Alimentadora")) {
                colorRuta = new Color(34, 139, 34);
            } else {
                colorRuta = Color.BLUE;
            }

            java.util.ArrayList<String> paradas = ruta.getListadoParadas();
            for (int i = 0; i < paradas.size() - 1; i++) {
                JButton botonOrigen  = obtenerBotonEstacion(paradas.get(i));
                JButton botonDestino = obtenerBotonEstacion(paradas.get(i + 1));
                if (botonOrigen != null && botonDestino != null) {
                    panelMapa.agregarTramo(botonOrigen, botonDestino, colorRuta);
                }
            }
        }

        seccionMapa.add(panelMapa);

        // Ponemos los botones en primer plano y el panel de líneas al fondo
        for (java.awt.Component c : seccionMapa.getComponents()) {
            if (c instanceof JButton) {
                seccionMapa.setComponentZOrder(c, 0);
            }
        }
        seccionMapa.setComponentZOrder(panelMapa, seccionMapa.getComponentCount() - 1);

        seccionMapa.revalidate();
        seccionMapa.repaint();
    }
}